### ISSUE TITLE
Feature request: Settings widget

### ISSUE THREAD

**Issue by JordanLongstaff** [jurialmunkey/skin.horizon#10]
I would like there to be a default widget for Settings, containing one item for every category in the Settings screen. My only workaround would be to compose a submenu with every category therein, and then have Categories as a default widget, but that would affect every home menu item, not just Settings. In fact, it'd be nice to have two formats for this format: one in a single row like most widgets, and one that takes up the entire screen like the Weather widget.

I'm even fine with making the widget myself, so long as there's a tutorial somewhere...

**Comment by jurialmunkey** [comment]
I am currently very busy with work, but this is already a planned feature that should make an appearance some time in the next month or so.

**Comment by jurialmunkey** [comment]
Added :)

https://i.imgur.com/z2KPj9g.png

**Comment by JordanLongstaff** [comment]
Ooh, looks nice! I'll have to update again soon.
