### ISSUE TITLE
Settings menu disappears when mouse moves off enabled menu items

### ISSUE THREAD

**Issue by JordanLongstaff** [jurialmunkey/skin.horizon#11]
As you can see in the attached screenshots, I have my mouse on "Backup / Restore" at the bottom of the left menu, showing the menu items on the right. However, when I try to move my mouse over, the menu items on the right disappear.
![screenshot003](https://user-images.githubusercontent.com/7563922/32142030-5f4562b6-bc65-11e7-861d-08343cc16dae.png)
![screenshot004](https://user-images.githubusercontent.com/7563922/32142031-5f74a01c-bc65-11e7-8375-3f42eeed6650.png)

The same goes for when I try to move my mouse down over disabled menu items, as shown here:
![screenshot005](https://user-images.githubusercontent.com/7563922/32142039-7916c9aa-bc65-11e7-8b54-f9ee1343f471.png)
![screenshot006](https://user-images.githubusercontent.com/7563922/32142040-7952b604-bc65-11e7-950e-cc7e914780ec.png)

EDIT: This issue appears to be exclusive to the Skin Settings menu. In all other submenus of Settings, everything worked fine.

**Comment by jurialmunkey** [comment]
Should be fixed now.
Sorry for the long wait!

**Comment by JordanLongstaff** [comment]
It's fixed alright! So is the music seeking OSD issue. Thanks!
