### ISSUE TITLE
PVR Widgets load and disappear

### ISSUE THREAD

**Issue by nilleiz** [jurialmunkey/skin.horizon#13]
Hi, 

I am on latest libreelec 8.2 Kodi 17.5. 
Skin helper service is version 1.0.36.016.
On every PVR related widget I try in main menu there is this issue that when going to live TV the widgets show that they're loading. After some seconds the areas where the widget should be disappears and only categories widget is shown.

I can provide a log if someone can tell me what exactly is needed.

Kind regards.

**Comment by jurialmunkey** [comment]
Do the same widgets work in other skins?

I don't have a functional pvr setup currently, so this is difficult for me to test.
