### ISSUE TITLE
Feature request: Search and Power buttons

### ISSUE THREAD

**Issue by JordanLongstaff** [jurialmunkey/skin.horizon#18]
I'd like to see some standard buttons in the GUI for Search and the Power menu, similar to the Estuary skin. As this screenshot shows, there's plenty of room for these buttons within the yellow rectangle:

![kodi screenshot](https://user-images.githubusercontent.com/7563922/33155794-8397c4aa-cfc1-11e7-9511-795d6126ba5e.png)

I can't include Search or Power as items in the main menu, because I'd have too many menu items (see also: [https://github.com/jurialmunkey/skin.horizon/issues/9](url)). Currently my only workaround is to have them as submenu items. I'd prefer having them as standard buttons. I'll leave it up to you whether or not to add a Settings button also.

To be clear, for the Power button, I'd prefer that it would open the Shutdown menu rather than immediately terminating Kodi.

**Comment by jurialmunkey** [comment]
I've already been working on this. Not quite finished, but I pushed the current state to a separate branch. If you checkout the topbar-icons branch you can see the current state
https://github.com/jurialmunkey/skin.horizon/tree/topbar-icons

**Comment by jurialmunkey** [comment]
Okay I made it an option which is disabled by default. You can turn it on in "Skin Settings > Home > Show search, settings, power icons". Let me know how it goes.
