### ISSUE TITLE
Cast picture not showing

### ISSUE THREAD

**Issue by darksiovish** [jurialmunkey/skin.horizon#20]
Hi thanks for the amazing skin first,
The cast picture doesn't show up using the info menu, using the extended info add-on brings up everything but the native skin info menu doesn't bring them up

**Comment by jurialmunkey** [comment]
Does it show in Estuary?

**Comment by darksiovish** [comment]
Sorry, you are absolutely right, I thought it was the skin because the add-on  updated when I set the skin but it has nothing to do with it, again thanks for the amazing work

**Comment by jurialmunkey** [comment]
No worries. Glad you are enjoying the skin! 😃
