### ISSUE TITLE
Menu retracts if mouse isn't hovering over top icons

### ISSUE THREAD

**Issue by JordanLongstaff** [jurialmunkey/skin.horizon#21]
Great work on the Search, Settings and Power buttons! Unfortunately, when using the mouse, it has to be hovering over the circular area of the buttons or else the menu slides to the left. It would be a lot easier to use if the menu stayed put while the mouse was just within that rectangle.

**Comment by jurialmunkey** [comment]
Should be fixed now.

**Comment by JordanLongstaff** [comment]
Much better! Thank you!
