### ISSUE TITLE
In progress Movies?

### ISSUE THREAD

**Issue by super94i** [jurialmunkey/skin.horizon#5]
Hello, I can't seem to find it. I really like this solid skin, and want that feature if possible.

Thanks.

**Comment by bartolomesoriano** [comment]
super94i, you can make a smart playlist for in progress movies and use it as a menu item, submenu item or widget.

**Comment by jurialmunkey** [comment]
Skin Helper Widgets also provides an In-Progress option for Movies.
In customisation screen:
Default Widgets > Skin Helper Widgets > Movies > In Progress Movies.

If you want to add it as a menu item through Choose Shortcut:
Add-on > Video Add-on > Skin Helper Widgets > Movies > In Progress Movies

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!
