### ISSUE TITLE
Artwork and logo all black

### ISSUE THREAD

**Issue by Satris404** [jurialmunkey/skin.horizon#6]
Every time I use the skin, after some browsing, many logo, icons and fanart go all black. Reloading the skin bring that back to normal, but will get black again some time after. 
(by the way, it does the same in addons, not only on the home screen)
![img_4036](https://user-images.githubusercontent.com/29675522/31314163-8108903e-abc7-11e7-8fff-da012ece6e4f.JPG)
![img_4037](https://user-images.githubusercontent.com/29675522/31314167-810f04aa-abc7-11e7-978e-4a6c94617c8e.JPG)
![img_4033](https://user-images.githubusercontent.com/29675522/31314166-810ddc7e-abc7-11e7-8c99-1064382aac3b.JPG)
![img_4034](https://user-images.githubusercontent.com/29675522/31314164-810ce1b6-abc7-11e7-8db8-17ca5c6d2c1a.JPG)
![img_4035](https://user-images.githubusercontent.com/29675522/31314165-810dd94a-abc7-11e7-8e6b-151ef3adc8df.JPG)

**Comment by jurialmunkey** [comment]
Debug Log?

I'm guessing you are running out of RAM.

**Comment by Satris404** [comment]
Yeah, I’ll post the log later this week. And it makes sense! I have relatively lot of widget that gets information from long lists of data. It would be great if we could limit the number of information showed by the widgets on the menu. It would prevent running out of RAM, plus, it will load menu items much faster.

**Comment by Satris404** [comment]
[kodi.log](https://github.com/jurialmunkey/skin.horizon/files/1399887/kodi.log)

**Comment by jurialmunkey** [comment]
There are a lot of errors in that log. 
Not really a skin issue, but looks like it is a known issue:
https://forum.kodi.tv/showthread.php?tid=286836

Best bet is to ask for support in the Raspberry Pi area of the kodi forums:
https://forum.kodi.tv/forumdisplay.php?fid=166

**Comment by Satris404** [comment]
It's weird because I only have this problem with your skin... I'll investigate that. 

Despite this problem, it would be great if you could add the option to limit the number of item in widgets.

Thank you !

**Comment by jurialmunkey** [comment]
The option to limit the number of items in the widgets already exists in the latest git hub version. 
You can set the limit to 10, 25, or 50 in Skin Settings > Home (scroll down as it is at the bottom)

**Comment by Satris404** [comment]
I just saw ! sorry about that. Thank you !
