### ISSUE TITLE
Spoiler Free Options

### ISSUE THREAD

**Issue by trumblejoe** [jurialmunkey/skin.horizon#8]
Can't find an easy way to turn off the Plot / hide thumbnail images outside of the "PVR Guide" Setting, which I don't use and so I am hesitate to enable.

It would also be helpful to disable the TV Library top info-bar which tells me whether a show is 'Ended' or Returning.

**Comment by jurialmunkey** [comment]
Settings > Media > Videos > Show plot for unwatched items
