### ISSUE TITLE
Widgets fail to line up correctly in large main menu

### ISSUE THREAD

**Issue by JordanLongstaff** [jurialmunkey/skin.horizon#9]
I think Horizon normally has a cap on the number of items allowed when editing the home menu. However, it is possible to import a larger menu from another skin, to the point that you have to scroll up and down in Horizon. Then, if you scroll down, you see the wrong widgets when hovering over menu items. For example, if I had these three menu items in a row, each with a different set of widgets:

- Movies
- TV Shows
- Sports

If the menu is scrolled to the top, the correct widgets will be shown when hovering over each item. But if I scroll two steps down, and then hover over Sports, the Movies widgets will be shown. If I scroll one step down instead, the TV Shows widgets will be shown.
![screenshot000](https://user-images.githubusercontent.com/7563922/32141431-4b82dcea-bc56-11e7-94bc-133c387da504.png)
![screenshot001](https://user-images.githubusercontent.com/7563922/32141429-48887e28-bc56-11e7-80f9-139594814455.png)
![screenshot002](https://user-images.githubusercontent.com/7563922/32141430-4b5883aa-bc56-11e7-8f08-58e3070596c2.png)

**Comment by jurialmunkey** [comment]
12 items x 8 widgets = 96 widgets. This already puts a lot of strain on the system, so this is one of the reasons why there is a cap on the number of menu items. However, I can't prevent people getting around this cap by importing a setup from another skin. The only solution is to reduce the number of menu items you have to twelve.

**Comment by JordanLongstaff** [comment]
Reducing the number of menu items would be easier if there were standard buttons above the menu, in that grey rectangle next to the Kodi logo. It should be easy to add one for Settings, one for Search, and one for the Power menu.
